### ISSUE TITLE
Improve error messaging when CLI fails to connect to specified GraphQL server

### ISSUE THREAD

**Issue by aditya-konarde** [app-sre/qontract-reconcile#25] opened 2019-03-04 05:53 UTC
Currently, if the connection to the app-interface graphql server fails, we'll get an exception similar to the following. 

Example (removed actual cluster names and config names)
```
(venv) [akonarde@katana qontract-reconcile]$ qontract-reconcile --config=config.toml --dry-run openshift-resources-annotate masked masked ConfigMap masked
Traceback (most recent call last):
  File "/usr/lib64/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib64/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib64/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib64/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib64/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

What we should do: 
Handle the exception and provide a better output, something along the lines of 'Could not connect to app-interface server specified in config.toml'

**Comment by maorfr** [comment] 2019-08-20 07:49
closing as duplicate of #110

**Closed by maorfr** 2019-08-20 07:49 UTC
